import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:3000/');
  await page.getByRole('button', { name: 'Prijava' }).click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('test101@gmail.com');
  await page.getByRole('textbox', { name: 'Lozinka' }).click();
  await page.getByRole('textbox', { name: 'Lozinka' }).fill('lozinka');
  await page.getByRole('button', { name: 'Prijavi se' }).click();
  await page.getByRole('button', { name: 'Dodaj recept' }).click();
  await page.getByRole('textbox', { name: 'npr. Brza Pasta Carbonara' }).click();
  await page.getByRole('textbox', { name: 'npr. Brza Pasta Carbonara' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'npr. Brza Pasta Carbonara' }).fill('B');
  await page.getByRole('textbox', { name: 'npr. Brza Pasta Carbonara' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'npr. Brza Pasta Carbonara' }).fill('Brza ');
  await page.getByRole('textbox', { name: 'npr. Brza Pasta Carbonara' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'npr. Brza Pasta Carbonara' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'npr. Brza Pasta Carbonara' }).fill('Brza pileća jetra na tavi');
  await page.getByRole('textbox', { name: 'Kratki opis recepta...' }).click();
  await page.getByRole('textbox', { name: 'Kratki opis recepta...' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Kratki opis recepta...' }).fill('J');
  await page.getByRole('textbox', { name: 'Kratki opis recepta...' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Kratki opis recepta...' }).fill('Jednostavan proteinski recept za ljubitelje mesa.');
  await page.getByPlaceholder('30').click();
  await page.getByPlaceholder('30').fill('30');
  await page.getByPlaceholder('5.00').click();
  await page.getByPlaceholder('5.00').fill('7.23');
  await page.getByPlaceholder('kcal').click();
  await page.getByPlaceholder('kcal').fill('300');
  await page.locator('input[name="protein"]').click();
  await page.locator('input[name="protein"]').fill('23');
  await page.locator('input[name="carbs"]').click();
  await page.locator('input[name="carbs"]').fill('44');
  await page.locator('input[name="fat"]').click();
  await page.locator('input[name="fat"]').fill('9');
  await page.getByRole('textbox', { name: 'Počni tipkati naziv sastojka' }).click();
  await page.getByRole('textbox', { name: 'Počni tipkati naziv sastojka' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Počni tipkati naziv sastojka' }).fill('P');
  await page.getByRole('textbox', { name: 'Počni tipkati naziv sastojka' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Počni tipkati naziv sastojka' }).fill('Pileća');
  await page.locator('div').filter({ hasText: /^Pileća jetra$/ }).click();
  await page.getByPlaceholder('Količina').fill('198');
  await page.getByRole('button', { name: 'Dodaj sastojak' }).click();
  await page.getByRole('textbox', { name: 'Počni tipkati naziv sastojka' }).nth(1).click();
  await page.getByRole('textbox', { name: 'Počni tipkati naziv sastojka' }).nth(1).fill('ulje');
  await page.getByText('Suncokretovo ulje').click();
  await page.getByPlaceholder('Količina').nth(1).fill('1');
  await page.getByText('Tava', { exact: true }).click();
  await page.getByText('visokoproteinska').click();
  await page.getByRole('textbox', { name: 'Korak' }).click();
  await page.getByRole('textbox', { name: 'Korak' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Korak' }).fill('S');
  await page.getByRole('textbox', { name: 'Korak' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Korak' }).fill('Stavi malo ulja na tavu');
  await page.getByRole('button', { name: 'Dodaj korak' }).click();
  await page.getByRole('button', { name: 'Dodaj korak' }).press('CapsLock');
  await page.getByRole('button', { name: 'Dodaj korak' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Korak 2...' }).click();
  await page.getByRole('textbox', { name: 'Korak 2...' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Korak 2...' }).fill('D');
  await page.getByRole('textbox', { name: 'Korak 2...' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Korak 2...' }).fill('Dodaj pileća jetra i peci dok nisu gotova');
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('button', { name: 'Objavi recept' }).click();
  await page.getByRole('button', { name: 'Moji recepti' }).click();
});